services:
  - type: worker
    name: password-tool-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m run
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ANALYTICS_BOT_TOKEN
        sync: false
      - key: ANALYTICS_CHAT_ID
        sync: false
